#!/bin/bash
pkill dunst
dunst -config ~/.config/dunst/dunstrc &

notify-send -u critical Warning "Test message: critical test 1"
notify-send -u normal Info "Test message: normal test 2"
notify-send -u low Notice "Test message: low test 3"
